### PR TITLE
pass metadata block seq to .file

### PR DESCRIPTION
**Pull request by mafintosh**
adds `file(name, archiveOptions, seq)`

### CODE REVIEW

**Comment by pfrazee** [comment]
It's not wholly impossible that `seq` will get reused if you have multiple concurrent writes, is it?

**Comment by mafintosh** [comment]
no, it should always be unique

**Comment by mafintosh** [comment]
@pfrazee one thing to consider is adding a flag of some sorts that tells you if this is the latest version (i.e. if you are reading a file fx) but maybe we can add that later

**Comment by pfrazee** [comment]
Are you sure? What if I did:

```
archive.append(...)
archive.append(...)
```

The files have to be processed before the metadata is updated, dont they?

**Comment by mafintosh** [comment]
i meant in theory (that should run inside a mutex). there might be bugs!

**Comment by pfrazee** [comment]
Is this the only thing that would require us to write in a mutex? Or did we already need to use a mutex?

**Comment by mafintosh** [comment]
we already need to

**Comment by pfrazee** [comment]
Wait really? Does that need to be done by the API consumer, aka do I need to add mutexes to beaker?

**Comment by mafintosh** [comment]
No, there is an internal one. The write streams / .append will simply pause while a single one is being processed

**Comment by pfrazee** [comment]
Oh I see. Ok. Let me review again...

**Comment by pfrazee** [comment]
Ok how would this work on read() ? Does bisect() get called during open if you're reading?

**Comment by mafintosh** [comment]
same as it works now. bisect is called if a block is being replicated and you don't know which file it belongs to

**Comment by pfrazee** [comment]
What I'm wondering is, how do we control which version is being read? It looks like metadata.blocks is always being used, which works for writes but not for reads -- except in bisect.

(Not at all to be critical: Im having some trouble groking this code, I think it could use a refactor.)

**Comment by mafintosh** [comment]
metadata.blocks is only used for append/writes (it's the latest version - metadata will be stored at that seq). seq just always points to the metadata index the current version is being stored at

**Comment by mafintosh** [comment]
you would just write data to `filename.{seq}` to have unique filenames per version

**Comment by pfrazee** [comment]
> seq just always points to the metadata index the current version is being stored at

That doesnt seem to be the case though. What's getting passed into file() as seq is the `metadata.blocks`, which makes sense for the write, but for the read it ought to be the sequence-number of the metadata-entry for that file, right?

**Comment by pfrazee** [comment]
How does createFileReadStream() correctly identify the file to read?

**Comment by mafintosh** [comment]
the bisect indirectly makes that happen. the metadata.blocks is only passed to writes

**Comment by mafintosh** [comment]
we can pass something else there if you think it is confusing. it just indicates the version it will be stored at.

**Comment by pfrazee** [comment]
Yeah Im just trying to make sure it's correct. So, when createFileReadStream happens, bisect() is used... wait is bisect a search for the entry? Oh man, it is isnt it

**Comment by pfrazee** [comment]
Ok that looks like it should work. We'll need a way to specify the revision later.

**Comment by pfrazee** [comment]
We should add some tests to the PR.

**Pull request merged**
