### PR TITLE
Add file and download-finished events (#53)

### PR DESCRIPTION
**Pull request by joehand**
### New Events:
- `file-downloaded`
- `file-appended`
- `download-finished`
- `finalized`

Plus docs and event tests.

@mafintosh before you suggested: 

>  good pr would be to add file-download, file-upload, file-downloaded events

What's the difference b/t file-download and file-downloaded? And what would someone use file-upload event for (or did you mean file-appended)?

### CODE REVIEW

**Comment by mafintosh** [comment]
@joehand `file-download` was when a chunk was downloaded for a file, but it seems we dont need that anymore with the new ui. `file-uploaded` was when a file was fully uploaded to another peer (we can add that later)

**Comment by clkao** [comment]
The description on `download-finished` for live is unclear about what 'updates finish' means.  Is it per metadata-feed change that finishes its content update?

**Comment by karissa** [comment]
what's the status on this one? are we able to resolve the conflicts?

**Comment by joehand** [comment]
This is pretty stale. I think we added similar events but can revisit if we need these again.

**Pull request closed without merging**
