### PR TITLE
hyperdrive 8

### PR DESCRIPTION
**Pull request by mafintosh**
(WIP PR)

* [x] replicate
* [ ] replicate (only latest + sparse)
* [x] unlink
* [x] history
* [x] checkout/version
* [x] readdir
* [x] readFile/writeFile
* [x] stat
* [x] lstat
* [x] createReadStream/createWriteStream
* [x] mkdir
* [x] rmdir
* [x] access
* [x] exists
* [ ] tests
* [x] write files as normal files

### CODE REVIEW

**Comment by juliangruber** [comment]
WOOOOOOOT ❤️

**Comment by somebody1234** [comment]
> unlink

:O I've been waiting for this for so long it's finally out :D
The others look very useful too

BTW you might want to close #99 now

**Comment by yoshuawuyts** [comment]
:tada: :tada: :tada: :tada: :tada:

**Comment by mafintosh** [comment]
Will be released on NPM in a few hours \o/

**Comment by pfrazee** [comment]
Awesome!!

So what's the status on the two unchecked boxes, "replicate (only latest + sparse)" and "tests" ?

**Comment by mafintosh** [comment]
@pfrazee tests and sparse mode in there. it is missing "only latest" but i'm adding that in a minor bump asap to just get this out the door

**Comment by mafintosh** [comment]
You can just use sparse mode to download latest anyway

**Comment by pfrazee** [comment]
Cool

**Comment by mafintosh** [comment]
I need to expose https://download.libsodium.org/doc/key_derivation/ before release as I want to derive the content secret key from the metadata secret key, so just waiting on that :)

**Comment by mafintosh** [comment]
In [sodium-native](https://github.com/mafintosh/sodium-native)

**Comment by mafintosh** [comment]
8 is now on npm!

**Pull request merged**
