### PR TITLE
Added peer-add and peer-removed events

### PR DESCRIPTION
**Pull request by RangerMauve**
This'll fix https://github.com/datproject/sdk/issues/41

### CODE REVIEW

**Comment by RangerMauve** [comment]
Thank you! Did this get published on NPM by any chance?

**Comment by mafintosh** [comment]
Just this once XD - v9.17.0

**Comment by RangerMauve** [comment]
Thank you! <3

**Comment by RangerMauve** [comment]
(Doesn't look like it got published on NPM. 😅)

**Pull request merged**
